/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NCol: typeof import('naive-ui')['NCol']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NEl: typeof import('naive-ui')['NEl']
    NFlex: typeof import('naive-ui')['NFlex']
    NGi: typeof import('naive-ui')['NGi']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NGrid: typeof import('naive-ui')['NGrid']
    NGridItem: typeof import('naive-ui')['NGridItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NRow: typeof import('naive-ui')['NRow']
    NTooltip: typeof import('naive-ui')['NTooltip']
    NWatermark: typeof import('naive-ui')['NWatermark']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
