/*
 * 版权所有(c) Trih(HUA Haohui) 2025 - 2025
 * Copyright (c)Trih(HUA Haohui) 2025 - 2025, All Rights Reserved.
 */

// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
export interface Feeds {
	title: string
	id: number
	author_id: number
	nickname: string
	avatar: string
	cover_url: string
	height: number
	width: number
	like_num: number
	publish_time: number
}
export interface GetFeedListResponse {
	status: string
	feeds: Array<Feeds>
	total: number
}
export interface AdminRes {
	//状态
	status: string
	//操作人
	operator: string
}

export interface Auth {
	token: string
}

export interface ChangeMobileRequest {
	new_mobile: string
	verifyCode: string
}

export interface ChangeMobileResponse {
	status: string
}

export interface ChangePasswordRequest {
	new_password: string
}

export interface ChangePasswordResponse {
	status: string
}

export interface ChangeUserInfoRequest {
	nick_name: string // 昵称
	signature: string // 简介
	avatar: string // 头像
}

export interface ChangeUserInfoResponse {
	status: string
}

export interface ChangeUserTypeRequest {
	//用户id
	user_id: string
	//权限类型
	type: number
}

export interface CommentItem {
	id: number // 评论ID
	user_id: number // 用户ID
	nickname: string // 用户昵称
	avatar: string // 用户头像
	content: string // 评论内容(压缩富文本)
	like_count: number // 点赞数
	create_time: string // 创建时间
	ip_location: string // ip归属地
	sub_comments: Array<SubCommentItem> // 子评论列表
	sub_comment_count: number // 子评论总数
}

export interface CommentListRequest {
	article_id: number
	page?: number
}
export interface CommentListRequestParams {
	article_id: number // 文章ID
	page: number // 页码
	page_size: number // 每页数量
}

export interface CommentListResponse {
	comments: Array<CommentItem>
	total: number
}

export interface DeleteFeedRequest {
	id: number
}

export interface Feed {
	title: string
	id: number
	media_url: string
	media: MediaInfo
	like_num: number
	loaded: boolean
	user: FeedUser
}

export interface FeedDetail {
	title: string // 标题
	id: number // ID
	media_url: string // 封面
	content: string // 内容
	comment_num: number // 评论数
	like_num: number // 点赞数
	collect_num: number // 收藏数
	media: MediaInfo // 多媒体信息
	media_list: Array<string> // 多媒体列表
	user: FeedUser // 作者
	publish_time: number // 发布时间
	ip_location: string // ip归属地
}

export interface FeedUser {
	user_id: number
	user_name: string
	avatar: string
	type: number
}

export interface FollowListResponse {
	message: string
	follow_list: Array<User>
}

export interface FollowRequest {
	user_id: string
}

export interface FollowResponse {
	message: string
}

export interface GetFeedDetailResponse {
	Feed: FeedDetail
}

export interface GetIndexFeedsRequestParams {
	os: number
	q: string
}

export interface GetIndexFeedsResponse {
	status: string
	feeds: Array<Feed>
}

export interface GetUpTokenRequestParams {
	t: string
}

export interface GetUpTokenResponse {
	token: string
}

export interface LikeCommentRequest {
	comment_id: number // 点赞目标
}

export interface LikeCommentResponse {
	status: string
}

export interface LoginMobilePassRequest {
	mobile: string
	password: string
}

export interface LoginRequest {
	user_id: number
	password: string
}

export interface LoginResponse {
	user_id: number
	user_name: string
	avatar: string
	signature: string
	type: number
	token: string
}

export interface MediaInfo {
	width: number
	height: number
}

export interface NewCommentRequest {
	content: string // 评论内容压缩过的富文本
	raw_ontent: string // 原始内容
	parent_id: number // 父评论ID
	parent_user_id: number // 父评论用户ID
	// 用户ID使用jwt
	article_id: number // 文章ID
}
export type NewCommentRequestParams = {
	content: string // 评论内容压缩过的富文本
	raw_content: string // 原始内容
	parent_id: number // 父评论ID
	parentUser_id: number // 父评论用户ID// 用户ID使用jwt
	article_id: number
}

export interface NewCommentResponse {
	status: string
}

export interface NewFeedRequest {
	title: string // 标题
	content: string // 富文本内容
	raw_content: string // 原始内容
	cover?: string // 封面
	cover_info?: MediaInfo // 封面信息
	media?: Array<string> // 图片
}

export interface NewFeedRequestHeaders {
	kip: string
}

export interface RegisterRequest {
	user_name: string
	password: string
	mobile: string
	verifyCode: string
	czj_code?: string // 邀请码用来绑定id
}

export interface RegisterResponse {
	user_id: number
	token: string
	user_name: string
	avatar: string
	signature: string
	type: number
}

export interface ShareFeedXHSResponse {
	nonce: string
	signature: string
	timestamp: string
}

export interface StatusResponse {
	status: string
}

export interface SubCommentItem {
	id: number // 评论ID
	user_id: number // 用户ID
	nickname: string // 用户昵称
	avatar: string // 用户头像
	content: string // 评论内容
	like_count: number // 点赞数
	create_time: string // 创建时间
	parent_id: number // 父评论ID
	parent_user_id: number // 父评论用户ID
	ip_location: string // ip归属地
	reply_to_nickname: string // 回复对象的昵称
}

export interface User {
	Nickname: string // 昵称
	Signature: string // 简介
	Avatar: string // 头像
	Type: number
}
export interface UserFeedsRequestParams {
	os: number
	uid: number
	ftype: number
}

export interface UserInfoResponse {
	user_id: number
	user_name: string
	avatar: string
	type: number
	status: number
	v_note: string
	signature: string
	feed_count: number
	fans_count: number
	follow_count: number
	ip_location: string
	active_time: number
	ban_time: number
}

export interface UserRelationResponse {
	like_feeds: string // 点赞帖子
	collect_feeds: string // 收藏帖子
	like_comments: string // 点赞评论
	follow_users: string // 关注列表
}

export interface VerifyCodeRequest {
	mobile: string
}

export interface VerifyCodeResponse {
	status: string
	temp_code: string
}

export interface TestRequest {
	content: string
}

export interface TestResponse {
	content: string
}
